# Create a docker compose for testing Meilisearch
version: "3"

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
      - MEILI_LOG_LEVEL=ERROR
      - MEILI_ENV=development
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

volumes:
  meili_data:
