name: Tests

on:
  pull_request:
  push:
    branches:
      - trying
      - staging
      - main

jobs:
  lint_tests:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run JS/TS linter
        run: yarn lint

  build_test:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: dist  # Ou outro diretório de build
          key: build-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            build-${{ runner.os }}-
      - name: Build project
        run: yarn build

  scrap_tests:
    runs-on: ubuntu-latest
    name: Crawler tests
    services:
      meilisearch:
        image: getmeili/meilisearch:latest
        env:
          MEILI_MASTER_KEY: "masterKey"
          MEILI_NO_ANALYTICS: "true"
        ports:
          - "7700:7700"
    strategy:
      fail-fast: false
      matrix:
        node: ["20"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: dist
          key: build-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            build-${{ runner.os }}-
      - name: Run playground
        run: yarn playground:start &
      - name: Run default strategy scraper
        run: yarn start -p misc/config_examples/docusaurus-default.json
      - name: Run docsearch strategy scraper
        run: yarn start -p misc/config_examples/docusaurus-docsearch.json
      - name: Run scrapix server
        run: yarn serve &
      - name: Wait
        run: sleep 5
      - name: Call scrapix server
        run: sh .github/scripts/scrapix_server_call_check.sh
